-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 10:25:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto_integrador` ;
USE `db_projeto_integrador` ;

-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_usuario` (
  `idtb_usuário` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_usuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_postagem` (
  `idtb_postagem` INT NOT NULL AUTO_INCREMENT,
  `tb_tema_idtb_tema` INT NOT NULL,
  `tb_usuário_idtb_usuário` INT NOT NULL,
  `publicacao` VARCHAR(45) NULL,
  `convite` VARCHAR(45) NULL,
  `evento` VARCHAR(45) NULL,
  `comunidade` VARCHAR(45) NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idtb_postagem`, `tb_tema_idtb_tema`, `tb_usuário_idtb_usuário`),
  INDEX `fk_tb_postagem_tb_tema_idx` (`tb_tema_idtb_tema` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuário1_idx` (`tb_usuário_idtb_usuário` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_tema`
    FOREIGN KEY (`tb_tema_idtb_tema`)
    REFERENCES `db_projeto_integrador`.`tb_tema` (`idtb_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuário1`
    FOREIGN KEY (`tb_usuário_idtb_usuário`)
    REFERENCES `db_projeto_integrador`.`tb_usuario` (`idtb_usuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_informações_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_informações_instituicao` (
  `idtb_informações` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `endereço` VARCHAR(100) NOT NULL,
  `email_comercial` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(50) NULL DEFAULT 'Inexistente',
  `tb_postagem_idtb_postagem` INT NOT NULL,
  `tb_postagem_tb_tema_idtb_tema` INT NOT NULL,
  `tb_postagem_tb_usuário_idtb_usuário` INT NOT NULL,
  PRIMARY KEY (`idtb_informações`, `tb_postagem_idtb_postagem`, `tb_postagem_tb_tema_idtb_tema`, `tb_postagem_tb_usuário_idtb_usuário`),
  INDEX `fk_tb_informações_instituicao_tb_postagem1_idx` (`tb_postagem_idtb_postagem` ASC, `tb_postagem_tb_tema_idtb_tema` ASC, `tb_postagem_tb_usuário_idtb_usuário` ASC) VISIBLE,
  CONSTRAINT `fk_tb_informações_instituicao_tb_postagem1`
    FOREIGN KEY (`tb_postagem_idtb_postagem` , `tb_postagem_tb_tema_idtb_tema` , `tb_postagem_tb_usuário_idtb_usuário`)
    REFERENCES `db_projeto_integrador`.`tb_postagem` (`idtb_postagem` , `tb_tema_idtb_tema` , `tb_usuário_idtb_usuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projeto_integrador`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto_integrador`.`tb_tema` (
  `idtb_tema` INT NOT NULL AUTO_INCREMENT,
  `doação` VARCHAR(100) NULL,
  `visita` VARCHAR(45) NULL,
  `valor` DECIMAL(300) NULL,
  `tb_informações_instituicao_idtb_informações` INT NOT NULL,
  PRIMARY KEY (`idtb_tema`, `tb_informações_instituicao_idtb_informações`),
  INDEX `fk_tb_tema_tb_informações_instituicao1_idx` (`tb_informações_instituicao_idtb_informações` ASC) VISIBLE,
  CONSTRAINT `fk_tb_tema_tb_informações_instituicao1`
    FOREIGN KEY (`tb_informações_instituicao_idtb_informações`)
    REFERENCES `db_projeto_integrador`.`tb_informações_instituicao` (`idtb_informações`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
